### ISSUE TITLE
'Unexpected token *' error message in gulpfile

### ISSUE THREAD

**Issue by thoroc** [ivpusic/arch-orchestrator#2]
Hi,

I have just found your lib and tried it by simply calling it as follow:

```
var orchestrator = require('arch-orchestrator');
```

but I am already getting the following error message, before I even tried to use the var `orchestrator`:

```
E:\Projects\gulp-bootstrap\node_modules\arch-orchestrator\lib\cache.js:30
      this.fnCache[key] = function * () {
                                   ^
SyntaxError: Unexpected token *
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\Projects\gulp-bootstrap\node_modules\arch-orchestrator\lib\orchestrator.js:4:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

My aim was to use it instead of [`run-sequence`](https://github.com/OverZealous/run-sequence) in a gulpfile for ordered build task.

**Comment by ivpusic** [comment]
You need node 0.12 with harmony flag.
